### ISSUE TITLE
Integrate TinyUF2 into SAME54 bootloader and add CDC functions

### ISSUE THREAD

**Issue by tomwbarclay** [adafruit/tinyuf2#116]
Hi, I am attempting to integrate TinyUF2 into an existing bootloader on custom SAME54 board. Here are my issues,
A) I want to add 2 channels of CDC, and although I can get them to run when only using TinyUSB, I cant make them function as part of TinyUF2 despite the config option to include CDC. I believe its a config/enumeration issue.
B) The board will be enclosed in a box so I need the CDC channels to communicate with the board, as it does not have any user buttons, to start the upgrade process and erase the flash ready for the UF2 file (drag and drop on WIndows) copy to the target. I am looking at the possibility of executing the flash erase on arrival of the the first UF2 block, but as this takes some time I am concerned that the USB connection wout time out.
C) I am baffled as to the role of the HID interface as it seems to only provide debug message functionality.

Any guidance my misconceptions and on potential strategies to achieve the above would be gratefully received.

**Comment by hathach** [comment]
> Hi, I am attempting to integrate TinyUF2 into an existing bootloader on custom SAME54 board. Here are my issues,
> A) I want to add 2 channels of CDC, and although I can get them to run when only using TinyUSB, I cant make them function as part of TinyUF2 despite the config option to include CDC. I believe its a config/enumeration issue.

It is hard to comment without the actual code, could you make an PR to add SAME54 port. That would make it easier to analyze problem. Also that would separate your existing bootloader and make it easier to troubleshoot. If you believe it is config/enumeration issue, what have you tried to narrow it down, analyzer or getting the tinyusb log out ?

> B) The board will be enclosed in a box so I need the CDC channels to communicate with the board, as it does not have any user buttons, to start the upgrade process and erase the flash ready for the UF2 file (drag and drop on WIndows) copy to the target. I am looking at the possibility of executing the flash erase on arrival of the the first UF2 block, but as this takes some time I am concerned that the USB connection wout time out.

It is up to you to decide, I have no idea about your hardware

> C) I am baffled as to the role of the HID interface as it seems to only provide debug message functionality.

HID is not used at all, it may be implemented later as hf2 (part of uf2 spec). But haven't done so.
