### ISSUE TITLE
TinyUF2 release to coincide with CircuitPython 7.0.0

### ISSUE THREAD

**Issue by durapensa** [adafruit/tinyuf2#145]
Disussed with @tannewt on Discord, would be useful to have precompiled TinyUF2 binaries for the new boards since TinyUF2 0.5.1 (Morph esp240, Lolin S2 Mini, & Espressif HMI devkit), to coincide with the upcoming CircuitPython 7.0.0 release.

**Comment by hathach** [comment]
released as 0.5.2 https://github.com/adafruit/tinyuf2/releases/tag/0.5.2
