### ISSUE TITLE
Adding support for stm32f103 generic bluepill 

### ISSUE THREAD

**Issue by pathnirvana** [adafruit/tinyuf2#146]
I am not sure if this is technically possible but it would be very useful since it is a very popular board.

**Comment by evildave666** [comment]
Are you aware of this project? tinyuf2 on an f103 probably wouldn't leave enough user space to be useful for anything.

https://github.com/mmoskal/uf2-stm32f103

**Comment by hathach** [comment]
closed due to lack of activities. it is possible but we don't have the time to do so. If anyone make an PR, I will be happy to review.
