### ISSUE TITLE
ESP32-SX Single OTA partition

### ISSUE THREAD

**Issue by 203Null** [adafruit/tinyuf2#202]
Is the ota_1 partition used by tinyUF2 in any way? If not, can we free it for other uses?

I know in the official documents, at least two OTA partitions are required but I don't think we really need two for tinyUF2. 
When flashing fails, just revert back to TinyUF2 at the factory partition and let the user reflash it,

**Comment by hathach** [comment]
you could add then pick noota partitions layout for your board. I did answer similar question here https://github.com/adafruit/tinyuf2/issues/227#issuecomment-1168885128 . The tinyuf2 may need a few adjustment but not thing major.
