### ISSUE TITLE
CI Deprecation Warnings

### ISSUE THREAD

**Issue by tekktrik** [adafruit/tinyuf2#276]
### Operating System

Others

### INFO_UF2.TXT

N/A

### What happened ?

GitHub Actions is deprecating Node.js 12 and also changing how outputs are set in steps.

### How to reproduce ?

Run Actions.

**Comment by tekktrik** [comment]
I can work on this but wanted an issue so I wouldn't forget.

**Comment by hathach** [comment]
iirc we can fix this by update `actions/setup-python@v4` . @tekktrik have you tried any code changes just yet, if not, I could try to make an PR to see if that works out.

**Comment by tekktrik** [comment]
I've updated versions for standard action steps like `actions/setup-python` and 'actions/checkout` in the CircuitPython libraries without issue.  Same thing for how the outputs of steps are set, no issues there either.
