### ISSUE TITLE
Update GitHub Actions to Upload to Amazon S3

### ISSUE THREAD

**Issue by makermelissa** [adafruit/tinyuf2#277]
In order to make the bootloader accessible for ESP32 Devices to the New CircuitPython Installer I'm working on and get around CORS issues, GitHub Actions needs to be updated to upload the release files to Amazon S3 like we do with CircuitPython Libraries and Firmware currently.

This should be fairly easy as we already have it implemented in other repos.

**Comment by hathach** [comment]
implemented by #278
