### ISSUE TITLE
Tinyuf2 bootloader size

### ISSUE THREAD

**Issue by Pillar1989** [adafruit/tinyuf2#30]
I know each board is different, can you give us some reference sizes for  typical board?

**Comment by hathach** [comment]
As you said, there is really no general size for all. Though you could look at the ci build log of a specific board for its size (at the end of build step) https://github.com/adafruit/tinyuf2/actions

**Comment by Pillar1989** [comment]
![image](https://user-images.githubusercontent.com/4081906/100182175-f4eeaa80-2f16-11eb-9de8-45bdfe4eab64.png)
Minimum 49K, this is not tIny at all.

**Comment by hathach** [comment]
Which board you are talking about, you should check its build log in ci as I mentioned earlier rather than looking at the artifacts which bundles several binaries. Also feel free to make your own bootloader.

**Comment by Pillar1989** [comment]
@hathach  I'm talking about the stm32f411ve_discovery board, I downloaded artifacts and its bin file, which is only 13.2kB. This is great, hopefully in the future, I can keep it under 8kB.  We plan to port it to this chip.
https://www.st.com/resource/en/datasheet/stm32h735ag.pdf
