### ISSUE TITLE
Build for Adafruit Qualia S3 board

### ISSUE THREAD

**Issue by tyeth** [adafruit/tinyuf2#358]
Hey there!
There doesn't seem to be an Adafruit Qualia build, the product item is 5800 (Adafruit Qualia ESP32-S3 for TTL RGB-666 Displays) https://www.adafruit.com/product/5800
One to add to the list I guess :)

**Comment by tyeth** [comment]
Having just flashed the factory reset bin file then double reset into uf2 bootloader it's shown up as the adafruit tft experimenter when Windows installed the device.
I was originally trying to install circuitpython on the qualia with the web-installer method which failed looking for a tiny uf2 qualia release zip

**Comment by hathach** [comment]
our bad, tftexperimental is prototype name of the board, we forgot to change it to qualia. PR #359 will address this, we will also bump up release after merged as well. Thank you for your issue.

**Comment by hathach** [comment]
PS: it is now available in release 0.18.1

**Comment by tyeth** [comment]
Thanks @hathach!
