### ISSUE TITLE
Add release support for 'ESP32-S3 Cam'

### ISSUE THREAD

**Issue by pbella** [adafruit/tinyuf2#364]
**Is your feature request related to a problem? Please describe.**
I have been having a frustrating time trying to find support for the 'ESP32-S3 Cam' board (an example can be found here: [https://www.aliexpress.us/item/3256805913061487.html](url))

**Describe the solution you'd like**
Ideally, a pre-built release.

**Describe alternatives you've considered**
Either a pre-built release for this board or clear instructions on how to build one that is appropriate for these boards would be appreciated.  If one of the existing releases already supports these boards my searches have not found it explicitly called out anywhere.

As these boards come in a variety of flash/PSRAM configurations, instructions  including any necessary modifications based on flash/PSRAM configuration would be appreciated.

**Additional context**
N/A

**Comment by hathach** [comment]
For 3rd party boards, please ask their maker to make the port. PR is welcome

**Comment by pbella** [comment]
> For 3rd party boards, please ask their maker to make the port. PR is welcome

Aren't the ESP32(-S3) Cam boards reference designs from Espressif?
