### ISSUE TITLE
Download missing for lolin s3 mini?

### ISSUE THREAD

**Issue by uecoding** [adafruit/tinyuf2#379]
I'm trying to download the bootloader for lolin s3 mini from [downloads](https://circuitpython.org/board/lolin_s3_mini/) it shows this link but it seems like the file doesn't exist anymore:
https://github.com/adafruit/tinyuf2/releases/download/0.18.1/tinyuf2-lolin_s3_mini-0.18.1.zip

Where can I find the correct bootloader?

**Comment by dhalbert** [comment]
It looks like there never was a Lolin S3 mini version of the bootloader created. There is a regular "Lolin S3" but not mini.

You can load the .bin: you don't have to use the UF2. The regular S3 version of the bootloader _might_ work, but I haven't looked to see what the board differences are.

**Comment by uecoding** [comment]
Well I erased the flash and uploaded combined.bin of regular lolin s3 and then did the reset but it doesn't show up as a new drive.

**Comment by uecoding** [comment]
Oh okay. I used the online installer and selected "Upgrade CircuitPython 8.2.10 Bin Only". Now it works
