### ISSUE TITLE
Add definition for the LilyGO T-Deck

### ISSUE THREAD

**Issue by mirkokral** [adafruit/tinyuf2#380]
**Is your feature request related to a problem? Please describe.**
Currently, there are no definitions for the T-Deck.

**Describe the solution you'd like**
I would like a definition for the lilygo t-deck

**Describe alternatives you've considered**
I use the yd-esp32s3 but it can get buggy and there are bad defs

**Comment by hathach** [comment]
we can't since we don't have the board. PR is welcome though

**Comment by mirkokral** [comment]
im gonna try to make one rn with the yd-esp32-s3 n8r8 as base because it already works
