### ISSUE TITLE
Start generating releases

### ISSUE THREAD

**Issue by dhalbert** [adafruit/tinyuf2#39]
Could we start producing numbered releases?

My motivation is that we have some version of TinyUF2 on this Learn Guide page: https://learn.adafruit.com/adafruit-magtag/install-uf2-bootloader, but I'm not sure if it includes the SCSI completion fix. Some MagTag Windows users are seeing the BOOT drive disappearing too quickly during UF2 copies, and I think that fix might help.

**Comment by hathach** [comment]
Yeah sure, I am off for vacation until next week. I will do as soon as I get back.

**Comment by hathach** [comment]
bootloader is version and assets are uploaded to release https://github.com/adafruit/tinyuf2/releases/tag/0.1.0

```
TinyUF2 Bootloader 0.1.0 - esp-idf (v4.3-dev-1197-g8bc19ba89) tinyusb (0.7.0-45-g4a2baf40)
Model: Espressif Saola 1R WROVER
Board-ID: ESP32S2-Saola1R-v1.2
```
