### ISSUE TITLE
STM32F4 self-update

### ISSUE THREAD

**Issue by hathach** [adafruit/tinyuf2#47]
self-update feature is implemented for esp32s2 and imxrt10xx but not stm32f4 just yet.

**Comment by charkster** [comment]
Is "self-update" the flash programming of the uf2 file to the application address?

**Comment by hathach** [comment]
yes, though it isn't supported yet. Currently it is only supported on esp32s2 and imxrt

**Comment by DuMaM** [comment]
How much it will differ from this one
https://github.com/adafruit/tinyuf2/pull/144

**Comment by Bhav97** [comment]
@DuMaM There won't be a lot of difference. 
The erase range would change to 64K, the program function would change to something out of the F7 HAL library and the flash sector and page sizes need to be taken into account.
