### ISSUE TITLE
Compile error (fatal error: hal/cpu_hal.h: No such file or directory)

### ISSUE THREAD

**Issue by T94T** [adafruit/tinyuf2#66]
I get an error when compiling in Ubuntu 18.04
```
fatal error: hal/cpu_hal.h: No such file or directory
 #include "hal/cpu_hal.h"  // for cpu_hal_get_cycle_count()
```

target board: espressif_saola_1_wroom
CMake version: 3.19.4
esp-idf: 6e776946d01ec0d081d09000c36d23ec1d318c06

**Comment by hathach** [comment]
duplicated to #27, use exact version of IDF in the submodules.
