### ISSUE TITLE
mimxrt: Add `nuke.bin` (and .uf2?)

### ISSUE THREAD

**Issue by jepler** [adafruit/tinyuf2#95]
@ladyada would like a "nuke" program for this platform.  It would just issue the general flash erase command, so that uf2 would have to be re-loaded via sdphost or j-link.

**Comment by nxf58843** [comment]
The code just looks for the FCFB tag to trigger a reload.  Just take a file with 0x404 bytes of 0 and create a .UF2 file starting from 0x0.  
Using a 0x404 long file will make it universal since some parts look for the tag at 0x0 and some at 0x400.

**Comment by ladyada** [comment]
yah what we want is particularly special - a RAM-loading bin that sdphost can load in that will call chip erase. there are some times you really just want to start over from the beginning :)

**Comment by nxf58843** [comment]
All the pieces to do that are in the existing code.  Let me know if you need help.

**Comment by ladyada** [comment]
@hathach please make an attempt and we'll ask @nxf58843 for help if we need advice :)

**Comment by hathach** [comment]
the nuke binary is an application, doesn't sound like part of the bootloader project. Though I will try to fit it :sweat_smile: sweat_smile:

**Comment by nxf58843** [comment]
I've been noodling on this and I think we can add this function to the same standard bootloader image so that you can make it erase or force an overwrite when you load it.  We can add a tiny image that sets a flag and then jumps to the main image so you can pick the behavior by the jump address.  Or, has anyone considered adding USB CDC commands for erasing?  That would be more cross platform.

**Comment by hathach** [comment]
@nxf58843 thanks, regardless, I have added the PR for this https://github.com/adafruit/tinyuf2/pull/101 . Although it is technically not bootloader, but it is nice to have. I plan to generalize it so basically we will have 3 buidable binaries in this repo
- tinyuf2 bootloader (itself)
- self-udpate: for iMX RT it is actually the tinyuf2 itself. For other ports, it is an application than update the bootloader
- erase-app / nuke: to erase application firmware flash (factory reset), or even better if possible an additional nuke (erase-all) for imxrt

**Comment by hathach** [comment]
update: trigger it via USB Control message is nice as well, though It will be more problematic to get it done in the host than firmware. With the spaghetti of driver installing, claiming interface on wins/linux/macos etc ... It is just much easier to drag an pre-built uf2 to do the work in my experience.

**Comment by nxf58843** [comment]
sdphost also has a write register command.  We could use that to set flags that configure the behavior before jumping.  That would be simpler and save generating multiple images.  We could also specify what to erase (bl, app, everything) that way.  Only check the flags for sdp mode.

**Comment by hathach** [comment]
hmm, maybe we can have an magic number (similar to double tap), so that application can perform the factory reset by itself :thinking: :thinking:  seem like there is several ways to implement this. Of course, we can implement it all, just make sure we document it well :)

**Comment by hathach** [comment]
> sdphost also has a write register command. We could use that to set flags that configure the behavior before jumping. That would be simpler and save generating multiple images. We could also specify what to erase (bl, app, everything) that way. Only check the flags for sdp mode.

Yeah, I just think of this before seeing your reply. Therefore both app and sdphost can "execute" it. Also I was thinking for all other ports as well :)

**Comment by nxf58843** [comment]
We could probably even create a .UF2 file that writes the magic number to trigger it through MSD.

**Comment by hathach** [comment]
Right, nice suggestion, I will gather these all and put it into a pr
